#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Jul  9 01:58:02 2020

@author: sruthi
"""

import paho.mqtt.client as mqtt
import csv

# This is the Subscriber

def on_connect(client, userdata, flags, rc):
  print("Connected with result code "+str(rc))
  client.subscribe("sensors/evac/#")
  client.subscribe("sensors/health/#")
                   

def on_message(client, userdata, msg):
    
    message = str(msg.payload.decode('UTF-8'))
    message_topic = msg.topic
    #print("Message received from Topic:",message_topic)
    #print(message)
    if message_topic == "sensors/health/gas":
        gas_value = message
        print("gas_value",gas_value)
    elif message_topic == "sensors/health/pieze":
        piezo_value = message
        print(piezo_value)
    elif message_topic == "sensors/health/moisture":
        moisture_data = message
        print(moisture_data)
    elif message_topic == "sensors/health/crack":
        crack_data = message
        print(crack_data)
    elif message_topic == "sensors/evac/flame":
        flame_data = message
        print(flame_data)
    else:
        motion_data = message
        print(motion_data)
            
        
def on_actutaion():
    print("actutationdata")

    
#    if message_topic == "plan":
#        print(message)
#    elif message_topic == "sensors/evac":
#        print(message)
#    else:
#        print(message)

#    client.disconnect() 
    
client = mqtt.Client()
client.connect("192.168.0.163",1883,60)
client.on_connect = on_connect
client.on_message = on_message



client.loop_forever()